##show_sql은 운영환경에서 sout으로 나옴 그래서 logging으로 찍어야함
##ddl-auto : create 전략은 로컬환경에서만 사용해야함. 테이블을 만들때 기존에 있던건 삭제하고 다시 만들기 때문에
##    url : jdbc:h2:mem:test 이건 테스트 환경에서 실행해도 괜찮
#spring:
#  datasource:
#    #    url 뒤에 MVCC = TRUE 설정 x
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      #      ddl - auto 는 자동으로 테이블을 만들어주는 기능
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        운영 환경에서는 로깅을 통해 출력해야 한다.
#        #        show_sql: true
#        format_sql: none
#
##이렇게 하면 hibernate가 만드는SQL이 다 보인다. 위 show_sql은 sout에서 보인다. 밑은 로거를 통해 찍는다.
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#
#
